### ISSUE TITLE
Remove Ruby code

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber-json-schema#2]
Hi @TimotheeVille and @CynthiaMaillard - well done adding the schema and tests!

I don't think this repo should contain any code or publish any libraries. 

This repo should be programming language agnostic, and its sole purpose should be to host and version the JSON Schema file(s).

So I propose we delete all the Ruby related code. Let me know what you think.

**Comment by TimotheeVille** [comment]
Thanks @aslakhellesoy. That's what we thought first but how to use it in code then if we can't import it?

**Comment by TimotheeVille** [comment]
Ok, you want it to be accessible through api of the SchemaStore. Make sense
